### ISSUE TITLE
Is the module "ev" missing ?

### ISSUE THREAD

**Issue by anasquazbary** [Llocer/llocer_tarification#1]
Hello @Llocer !

I tried to get your OCPI implementation, i could get all the modules in the pom.xml file but I can't find the "com.llocer.ev" dependency.

Can you show me how to get it please ? :)

Thank you !

**Comment by Llocer** [comment]
Hi, 

Thanks for your interest in this librarian.

Most of class in the different elements of the ocpp/ocpi start with com.llocer.ev

Could you say the specific missing class or compiler error?

**Comment by anasquazbary** [comment]
Thank you for your quick response.

For example, my compiler doesnt find when I am in the file OcpiTarification.java these classes : OcpiCdr, OcpiChargingPeriod etc and also MesurandEnum and OcppTransactionEventRequest

**Comment by Llocer** [comment]
Hi,

The classes you refer belongs to projects llocer_ocpi_json and llocer_ocpp_json.

These two librarians contains the json schemas that describes the ocpp and ocpi messages. From these schemas (in json syntax) the java source code is generared using tool jsonschema2pojo In this way, java pojo's are created. Finally, the java files are compiled and jar file is created.

All the necessary steps are included in the pom.xml of the projects. By example, maven generate and maven install will execute all steps.

**Comment by anasquazbary** [comment]
Oh ! Thank you it's working, i never used jsonschema2pojo before !
I can now try your implementation :)
